GET http://localhost:5050/api/users

###

POST http://localhost:5050/api/register
Content-Type: application/json


{
    "first_name": "dera",
    "last_name": "Emeka",
    "balance": 1000,
    "password": "12345",
    "email": "dera@gmail.com"
}

###

POST http://localhost:5050/api/login
Content-Type: application/json

{
  
    "password": "12345",
    "email": "alakai@gmail.com"
}

###

POST http://localhost:5050/api/61b7e923b6d26ffb64f2fe5c/transactions

###

POST http://localhost:5050/api/61b96536af7b1ec619291317/deposit/1000

###

POST http://localhost:5050/api/61b965dbaf7b1ec61929131b/transfer/61b96536af7b1ec619291317/50

###

POST http://localhost:5050/api/reverse/a717fb06-570a-4972-8994-dace49f17993
Content-Type: application/json

{
    
}

