GET http://localhost:5050/api/users

###

POST http://localhost:5050/api/register
Content-Type: application/json


{
    "username":"Pasqua",
    "balance": 200,
    "password": "459",
    "email": "chideraemeka4@gmail.com"
}

###
